cmake_minimum_required(VERSION 3.8)
project(pid_maze_solver)
set(CMAKE_CXX_STANDARD 17)
set(CMAKE_EXPORT_COMPILE_COMMANDS ON)
add_compile_options(-Wall -Wextra -Wpedantic)
find_package(ament_cmake REQUIRED)
find_package(rclcpp REQUIRED)
find_package(nav_msgs REQUIRED)
find_package(sensor_msgs REQUIRED)
find_package(geometry_msgs REQUIRED)
find_package(tf2 REQUIRED)
find_package(tf2_ros REQUIRED)
add_executable(pid_maze_solver src/pid_maze_solver.cpp)
target_include_directories(pid_maze_solver PRIVATE include)
ament_target_dependencies(pid_maze_solver rclcpp nav_msgs sensor_msgs geometry_msgs tf2 tf2_ros)
install(TARGETS pid_maze_solver DESTINATION lib/${PROJECT_NAME})
if(BUILD_TESTING)
 find_package(ament_cmake_gtest REQUIRED)
 ament_add_gtest(test_route test/test_route.cpp)
 target_include_directories(test_route PRIVATE include)
endif()
ament_package()
